name: "Build"

on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Build wheels
        run: uv build

      - name: Publish wheels
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}