name: "Build and publish new version"

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.9"

      - name: Install poetry
        run: pip install poetry --pre

      - name: Build wheels
        run: poetry build

      - name: Publish wheels
        run: poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PW }}
